# Site settings
title: Aracon Software Ltd
email: pvillega@aracon.com
description: > # this means to ignore newlines until "baseurl:"
  Software consultancy based in London. We develop the sotware you deserve.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://aracon.com" # the base hostname & protocol for your site
twitter_username: araconsoftware
github_username:  pvillega

# Build settings
markdown: kramdown
