# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://aracon.com
title: Aracon Software Ltd
email: pvillega@aracon.com
author: Pere Villega
description: > # "Software consultancy based in London.	
    We develop the software you deserve."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/araconsoftware
  - title: github
    url: https://github.com/AraconSoftware
  - title: linkedin
    url: https://uk.linkedin.com/in/perevillega

