# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://aracon.com
title: Araconwiss GmbH
email: pvillega@aracon.com
author: Pere Villega
description: > # "Software consultancy based in Basel, Switzerland.
    We develop the software you deserve."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/pvillega
  - title: github
    url: https://github.com/pvillega
  - title: linkedin
    url: https://uk.linkedin.com/in/perevillega
