# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://aracon.com
title: Aracon Software SL
email: pvillega@aracon.com
author: Pere Villega
description: > # "Software consultancy based in Basel, Switzerland.
    We develop the software you deserve."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: bluesky
    url: https://bsky.app/profile/perevillega.com
  - title: github
    url: https://github.com/pvillega
  - title: linkedin
    url: https://www.linkedin.com/in/perevillega/
